### ISSUE TITLE
Run USER command in Websphere Dockerfile

### ISSUE THREAD

**Issue by djohnston89** [sebastianfaulhaber/openshift-v3-showcase#2]
Is this still currently required with the latest Websphere Dockerfile?

```oc edit scc restricted
# Change the runAsUser.Type strategy to RunAsAny

**Comment by sebastianfaulhaber** [comment]
Just tried to run the sample on a couple of environments:

OpenShift Online -->  could not get it to work due to security restrictions.
CDK --> worked fine out of the box.

It seems to me, that the image still requires specials permissions.

Regards,
Sebastian
